eeutil.operfirma.ws.url=http://XXXX:XXXXX/eeutil-oper-firma/ws/EeUtilService?wsdl
eeutil.igae.rs.base.url=https://XXXX:XXXX/eeutil-igae
eeutil.igae.token.name=X-API-token 
eeutil.igae.token.value=XXXXX 

#Flag para llamadas a RUN (si false NO se llama a RUN para generar URL)
#Flag para tamano (solo se llama a RUN si el flag anterior estÃ¡ a TRUE y la URL supera el tamaÃ±o definido en este flat, si el tamaÃ±o es 0 se llama siempre a RUN)
#true => llamar a run, false=> no llamar a run
run.active=true
#run.active = true && size = 0 (se llama a run para cualquier tamano de url)
#run.active = true && size > 0 (se llama a run para tamano > X)
run.active.size=315
run.active.urlnoqr.size=35
run.alta.url=https://des-run-api.redsara.es/api/
run.original.url=https://des-run.redsara.es/
run.username = XXXXXX
run.password = XXXXX
#Numero de caracteres con los que se genera la clave de run.
run.alta.numbercharacterskey=7


#NO APLICA – solo libreoffice.active=false
eeutil.libreoffice.rs.base.url=XXXXXXXXX
eeutil.libreoffice.token.name=XXXXXX
eeutil.libreoffice.token.value=XXXXXX
libreoffice.active=false

eeutil.pdfatools.rs.base.url=https://XXXX:XXXX/eeutilpdfatools
eeutil.pdfatools.token.name=X-API-token-pdftools 
eeutil.pdfatools.token.value=XXXXXXX 