/* Copyright (C) 2012-13 MINHAP, Gobierno de España
   This program is licensed and may be used, modified and redistributed under the terms
   of the European Public License (EUPL), either version 1.1 or (at your
   option) any later version as soon as they are approved by the European Commission.
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
   or implied. See the License for the specific language governing permissions and
   more details.
   You should have received a copy of the EUPL1.1 license
   along with this program; if not, you may find it at
   http://joinup.ec.europa.eu/software/page/eupl/licence-eupl */

package es.mpt.dsic.eeutil.misc.consumer.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2017-06-15T12:26:02.203+02:00
 * Generated source version: 3.0.3
 * 
 */
@WebService(targetNamespace = "http://service.ws.inside.dsic.mpt.es/", name = "EeUtilService")
@XmlSeeAlso({ObjectFactory.class})
public interface EeUtilService {

    @WebResult(name = "FirmaProcesada", targetNamespace = "")
    @RequestWrapper(localName = "postProcesarFirma", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.mpt.dsic.eeutil.misc.consumer.model.PostProcesarFirma")
    @WebMethod(action = "urn:postProcesarFirma")
    @ResponseWrapper(localName = "postProcesarFirmaResponse", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.mpt.dsic.eeutil.misc.consumer.model.PostProcesarFirmaResponse")
    public byte[] postProcesarFirma(
        @WebParam(name = "aplicacionInfo", targetNamespace = "")
        es.mpt.dsic.eeutil.misc.consumer.model.ApplicationLogin aplicacionInfo,
        @WebParam(name = "Firma", targetNamespace = "")
        byte[] firma
    ) throws InSideException;

    @WebResult(name = "esPdfA", targetNamespace = "")
    @RequestWrapper(localName = "comprobarPDFA", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.mpt.dsic.eeutil.misc.consumer.model.ComprobarPDFA")
    @WebMethod(action = "urn:comprobarPDFA")
    @ResponseWrapper(localName = "comprobarPDFAResponse", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.mpt.dsic.eeutil.misc.consumer.model.ComprobarPDFAResponse")
    public java.lang.Boolean comprobarPDFA(
        @WebParam(name = "aplicacionInfo", targetNamespace = "")
        es.mpt.dsic.eeutil.misc.consumer.model.ApplicationLogin aplicacionInfo,
        @WebParam(name = "DocumentoEntrada", targetNamespace = "")
        es.mpt.dsic.eeutil.misc.consumer.model.DocumentoEntrada documentoEntrada,
        @WebParam(name = "nivelCompilacion", targetNamespace = "")
        java.lang.Integer nivelCompilacion
    ) throws InSideException;

    @WebResult(name = "FacturaProcesada", targetNamespace = "")
    @RequestWrapper(localName = "visualizarFacturae", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.mpt.dsic.eeutil.misc.consumer.model.VisualizarFacturae")
    @WebMethod(action = "urn:visualizarFacturae")
    @ResponseWrapper(localName = "visualizarFacturaeResponse", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.mpt.dsic.eeutil.misc.consumer.model.VisualizarFacturaeResponse")
    public es.mpt.dsic.eeutil.misc.consumer.model.SalidaVisualizacion visualizarFacturae(
        @WebParam(name = "aplicacionInfo", targetNamespace = "")
        es.mpt.dsic.eeutil.misc.consumer.model.ApplicationLogin aplicacionInfo,
        @WebParam(name = "Factura", targetNamespace = "")
        byte[] factura
    ) throws InSideException;

    @WebResult(name = "contenidoInfo", targetNamespace = "")
    @RequestWrapper(localName = "convertirTCNAPdf", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.mpt.dsic.eeutil.misc.consumer.model.ConvertirTCNAPdf")
    @WebMethod(action = "urn:convertirTCNAPdf")
    @ResponseWrapper(localName = "convertirTCNAPdfResponse", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.mpt.dsic.eeutil.misc.consumer.model.ConvertirTCNAPdfResponse")
    public es.mpt.dsic.eeutil.misc.consumer.model.ContenidoInfo convertirTCNAPdf(
        @WebParam(name = "aplicacionInfo", targetNamespace = "")
        es.mpt.dsic.eeutil.misc.consumer.model.ApplicationLogin aplicacionInfo,
        @WebParam(name = "TCNInfo", targetNamespace = "")
        es.mpt.dsic.eeutil.misc.consumer.model.TCNInfo tcnInfo
    ) throws InSideException;

    @WebResult(name = "PdfSalida", targetNamespace = "")
    @RequestWrapper(localName = "convertirPDFA", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.mpt.dsic.eeutil.misc.consumer.model.ConvertirPDFA")
    @WebMethod(action = "urn:convertirPDFA")
    @ResponseWrapper(localName = "convertirPDFAResponse", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.mpt.dsic.eeutil.misc.consumer.model.ConvertirPDFAResponse")
    public es.mpt.dsic.eeutil.misc.consumer.model.PdfSalida convertirPDFA(
        @WebParam(name = "aplicacionInfo", targetNamespace = "")
        es.mpt.dsic.eeutil.misc.consumer.model.ApplicationLogin aplicacionInfo,
        @WebParam(name = "DocumentoEntrada", targetNamespace = "")
        es.mpt.dsic.eeutil.misc.consumer.model.DocumentoEntrada documentoEntrada,
        @WebParam(name = "nivelCompilacion", targetNamespace = "")
        java.lang.Integer nivelCompilacion
    ) throws InSideException;
}
